### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by TheNexusDesigns** [Aeoll/FFmpegify#1]
Unfortunately, it doesn't work I changed the .reg like in your doc http://prntscr.com/hr2ih5 but it doesn't show up in the windows context menu on a right click would have been a very nice extension :/

**Comment by Aeoll** [comment]
Oops! The reg file was incorrect - I've edited it.

The issue was the reg file was setting HKEY_CLASSES_ROOT\Directory/shell instead of HKEY_CLASSES_ROOT\*\shell
This meant the command was added to the context menu for directories, rather than individual files.

Thanks for reporting, let me know if this works

**Comment by TheNexusDesigns** [comment]
Thanks now it shows up in individual files but I get an error message if I try to run it this is what I get from windows.

> There is no program associated with the file for execution. Install a suitable program or create a mapping under "Standard programs" in the Control Panel if a program is already installed.

I installed ffmpeg and added it to my environment path in windows. And I also installed the latest version of Python don't know why I get this message maybe I need to change something?

**Comment by TheNexusDesigns** [comment]
BTW I tested now some FFmpeg commands and it works in my command prompt, I just think it doesn't recognize the "ffmpegify.py" script but I'm not sure I'm new to phyton scripting btw it's a very cool extension and I think many people will love it. Because it makes working with 3d renders so much easier hope you can help me get it working and thank you very much for your effort and time working on this project 👍

**Comment by Aeoll** [comment]
Possibly check the registry entry is pointing to ffmpegify.py correctly?

You can also try to debug by running the script directly from the command line `python ffmpegify.py "/path/to/frame_0004.jpg"`

**Comment by TheNexusDesigns** [comment]
Yeah it's located correctly and I don't know how to debug the script just started with python scripting if I try this I get an error http://prntscr.com/hr7irq also the path in the .reg is 100% correct here is an image of my current setup http://prntscr.com/hr7iyn hope you can help me figuring it out

**Comment by Aeoll** [comment]
- The error in your first screenshot is because you have used a python shell rather than a standard cmd window. Try running the command with cmd (from the directory that contains ffmpegify.py)

I've just gone through the setup on a new machine and couldn't find your error. If you still have problems I would try installing Python36 and FFmpegify to the exact locations I suggested using?

**Comment by TheNexusDesigns** [comment]
Thanks yeah the script runs perfectly when executing in the cmd or PowerShell command prompt but not when I do a right-click in the explorer it does not work. Do you have an idea what might be causing it I think something here might be wrong? http://prntscr.com/hr8e2h here is a screen recording of the issue I get https://i.gyazo.com/5ed757d65b93d166bda8670d0cdcb58c.mp4 hope you can help me with this please I did a fresh installation of Python36 and FFmpeg and tested now many different settings with no success. And if Python36 or FFmpeg would have an error I think the script would not execute in the cmd terminal but it works with no issues there. I think there might be something wrong in the .reg file just an idea

**Comment by TheNexusDesigns** [comment]
I don't know what I did now but it works after a few restarts only thing I don't like is that once I run the script the preview is in very low quality especially when using renders with glow elements and transparency how can I bring the quality up because some previews that have glow with transparency have some very harsh lines can you please tell me how to change it as high quality .mp4 instead of .mov file it can have around 150mb for a 15 seconds video I would not mind the large filesize or longer encode time if I get a better preview using your script that would be the only thing other then that it's an amazing script and would help many people. I would also success you to change the file format to .mp4 for the export and bring the quality higher you can add it as the second file to your git repo like saying low preset .mov and high .mp4 preset that would help also many other people. Thanks for your time and help.

**Comment by TheNexusDesigns** [comment]
EDIT: You could do it like this

> ffmpegify-low-preset-mov.py

 and 

> ffmpegify-high-preset-mp4.py 

to have two presets to choose from but that's just an idea because I'm sure many people would love to have the option for higher quality preview and some other people would like to have fast render-time with low presets instead that way all people would be very happy. BTW and the last thing is can you add support for "tif" files I see the script supports "tiff" but not "tif" that's all. And thanks so much for your effort and time making this awesome script! 😃

**Comment by Aeoll** [comment]
Glad you've got it working!

I've added a couple of extra files with alternative ffmpeg settings. These both also add a premultiply filter to properly handle transparency.

If you would like to tweak the settings further this is a good reference: https://trac.ffmpeg.org/wiki/Encode/H.264

Thanks for the feedback :)

**Comment by TheNexusDesigns** [comment]
Thanks so much really appreciate your help it works now perfectly also the new mp4 HQ preset you added is so much better in quality, I tested it now on a few renders that use glow on transparency it's really amazing :) Also I just got a question if you run the extension and it failed because of not supported file format does it store any temp files ? just wanted to know or does it use no temp files in other directories ?

**Comment by Aeoll** [comment]
There are no temp files - if the file type is incorrect ffmpeg does not run at all

**Comment by TheNexusDesigns** [comment]
Ok that's awesome thanks one last very small thing I noticed is it possible to get a file name like

> test-render0000
> test-render0001
> test-render0002
> test-render0003

get recognized by the script as a sequence too. I know it works if I use . or _ or any other space but it would be very convenient if it would be possible to get it to work also with this type of file name above because some renders use names like this it's possible to rename it but it would be amazing if it could recognize this filetype name too only if possible. 

Thanks so much again really amazing work you put here

**Comment by Aeoll** [comment]
It should work already - did you try it? :)

**Comment by TheNexusDesigns** [comment]
I did some tests and unfortunately it does not work with this type of filename :)

**Comment by Aeoll** [comment]
I've just tested with this naming and it seems to work. However the frame finder is quite simple - it just searches backwards from the file extension until it no longer finds a digit.

This means it will work for "test-render0001.jpg" but not "test-render0001_.jpg" or "test-render0001extratext.jpg". I may look at fixing this in future

**Comment by TheNexusDesigns** [comment]
Awesome btw find another small bug if you have files like

> "test-render0001.jpg"
> "test-render0002.jpg" 
> "test-render0003.jpg" 

and have a file called "test-render.txt" or .exe or any other file extension in the same directory with the same file name just different extension for the log as an example the script stops working and doesn't execute I did now some tests other than that the script works awesome with no other bugs :)

**Comment by Aeoll** [comment]
This should be fixed with the latest commit so I'm closing the topic
