### ISSUE TITLE
Win 10 Open With issue

### ISSUE THREAD

**Issue by brokenkeyframe** [Aeoll/FFmpegify#2]
I have installed:
C:/Python36 (PATH enviroment works)
FFmpeg in C:/ffmpeg/bin
PyQt5
C:/FFmpegify

but when I run the script from context menu, I have dialog "Open with" and have to choose program. And it halts the process. Can you please help to solve this issue?

**Comment by Aeoll** [comment]
Hi,
Is ffmpeg also available to PATH? If you type 'ffmpeg' into a terminal does it run?
Also make sure the registry entry is pointing correctly to Python/Ffmpegify. Often with these issues it's an incorrect path somewhere.

**Comment by nrdpxl** [comment]
Yes the reg paths was pointing to the user dropbox :) I edited reg paths and now it works! Anyway thank you so much for such an useful script!!!
