### ISSUE TITLE
grey bg on image sequence that has alpha & small feature request 

### ISSUE THREAD

**Issue by TheNexusDesigns** [Aeoll/FFmpegify#3]
Hey, just wanted to ask can we get a black BG for alpha PNG sequences that gets converted as video using your plugin? because now If I use a render with alpha png sequence and convert it to a video I get a dark grey bg like this: ( where the alpha is) http://prntscr.com/l136i2 can we have it as black bg? 

**and one very small feature request:** could you please add an option to combine image sequence renders with audio say I got a png or jpg sequence in a folder and an audio file named "audio.mp3" or "audio.wav" can it combine the image sequence and the audio file as one video output would be amazing if that would be possible. Because it's very tedious to add the render in an editing software and then put the audio if that would be all possible using your plugin that would be amazing. Hope that would be possible :)

**Comment by Aeoll** [comment]
Transparency is handled with a premultiply filter. In theory it should be black - the slight brightness may be a limitation in the H.264 video conversion? 

I'll have a look at the audio, it shouldn't be too difficult.

**Comment by Aeoll** [comment]
I've pushed an initial update with audio support. The script will pick up the first .mp3 or .wav file it finds in the same directory as the image sequence. I think it would be useful to offset the audio so I'll also add this option to the FFmpegifySettings Dialog too.

**Comment by TheNexusDesigns** [comment]
thanks btw is there an option to increase the audio bitrate quality of the exported video currently it has an audio bitrate of 117kbps could you add an option to increase it, please other than that it's amazing.

**Comment by TheNexusDesigns** [comment]
and the grey BG is also when exporting as .mov not only .mp4 all renders that include alpha get a dark grey bg

**Comment by Aeoll** [comment]
I had another look at this - the premultiply filter is causing the issue and I couldn't find a way to fix it while leaving the filter on. I've added an option to the settings dialog to disable the alpha premult.

I've also set the default audio bitrate to 32kbps.

~Closing
